# Generated by Django 6.0.6 on 2026-09-06 05:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0010_remove_userbadge_badge_remove_quest_target_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('node_type', models.CharField(choices=[('entrance', 'Building Entrance'), ('junction', 'Walkway Junction'), ('gate', 'Campus Gate'), ('poi', 'Point of Interest')], default='junction', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(blank=True, help_text='Link this node to a building if it is an entrance node.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='navigation_nodes', to='buildings.building')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='NavigationPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', models.JSONField(help_text='List of [lng, lat] coordinate pairs forming the real walkway shape.')),
                ('distance_meters', models.FloatField(default=0.0, help_text='Total length of this path segment in meters (auto-calculated on save).')),
                ('is_accessible', models.BooleanField(default=True, help_text='Wheelchair/accessibility compatible.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('end_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_to', to='navigation.navigationnode')),
                ('start_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paths_from', to='navigation.navigationnode')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
