# Generated by Django 6.0.6 on 2026-09-28 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationnode',
            name='node_type',
            field=models.CharField(choices=[('entrance', 'Building Entrance'), ('junction', 'Walkway'), ('gate', 'Campus Gate'), ('poi', 'Point of Interest')], default='junction', max_length=50),
        ),
    ]
