# Generated by Django 5.2.1 on 2026-10-03 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_alter_navigationnode_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampusPerimeter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Western Mindanao State University', max_length=255)),
                ('coordinates', models.JSONField(default=list, help_text='Closed list of [lng, lat] coordinate pairs forming the custom campus perimeter polygon.')),
                ('fill_color', models.CharField(default='#111827', help_text='Color of the masked area outside the campus.', max_length=50)),
                ('fill_opacity', models.FloatField(default=0.65, help_text='Opacity of the outside mask between 0.0 and 1.0.')),
                ('stroke_color', models.CharField(default='#B21830', help_text='Color of the boundary stroke line.', max_length=50)),
                ('stroke_width', models.FloatField(default=2.5, help_text='Width of the boundary stroke line in pixels.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
