# Generated by Django 6.0.6 on 2026-06-21 11:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('color_hex', models.CharField(blank=True, help_text='Hex color for map pins, e.g. #7F0303', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('HIDDEN', 'Published (Hidden)'), ('VISIBLE', 'Published (Visible)')], default='DRAFT', help_text='Drafts can be saved without coordinates/slugs.', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='If false, shows building as closed/inactive')),
                ('model_file', models.FileField(blank=True, null=True, upload_to='models/')),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('model_file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('model_active', models.BooleanField(default=False)),
                ('hotspots', models.JSONField(blank=True, default=list)),
                ('qr_code_secret', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departments', models.ManyToManyField(blank=True, related_name='buildings', to='buildings.department')),
                ('primary_department', models.ForeignKey(blank=True, help_text='Determines the map pin color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_buildings', to='buildings.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Geofence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('radius_meters', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geofences', to='buildings.building')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('hint', models.TextField()),
                ('reward_points', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='buildings.building')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TriviaFact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('fact', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_facts', to='buildings.building')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='buildings.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('model', '3D Model'), ('panorama', 'Panorama Image'), ('image', 'Building Image')], max_length=20)),
                ('file', models.FileField(upload_to='assets/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA256 hash for cache invalidation', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='buildings.building')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['building', 'asset_type', 'is_active'], name='buildings_b_buildin_8b3dc8_idx')],
            },
        ),
        migrations.CreateModel(
            name='BuildingUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('geofence', 'Geofence'), ('admin', 'Admin'), ('role_access', 'Role Access'), ('qr', 'QR Scan')], default='geofence', max_length=20)),
                ('last_validated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='buildings.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'indexes': [models.Index(fields=['user', 'building'], name='buildings_b_user_id_02212d_idx')],
                'unique_together': {('user', 'building')},
            },
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['slug'], name='buildings_b_slug_36fc27_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['is_active'], name='buildings_b_is_acti_3c43aa_idx'),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['status'], name='buildings_b_status_93224f_idx'),
        ),
        migrations.AddIndex(
            model_name='geofence',
            index=models.Index(fields=['building', 'is_active'], name='buildings_g_buildin_2a4ea1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userquestprogress',
            unique_together={('user', 'quest')},
        ),
    ]
