# Generated by Django 6.0.6 on 2026-06-27 13:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji icon e.g. 🏅', max_length=10)),
                ('color_hex', models.CharField(default='#FFD700', max_length=7)),
                ('trigger', models.CharField(choices=[('first_unlock', 'First Building Unlocked'), ('unlocks_5', '5 Buildings Unlocked'), ('unlocks_10', '10 Buildings Unlocked'), ('unlocks_all', 'All Buildings Unlocked'), ('first_quest', 'First Quest Completed'), ('quests_5', '5 Quests Completed'), ('quests_10', '10 Quests Completed'), ('points_100', '100 Points Earned'), ('points_500', '500 Points Earned'), ('points_1000', '1000 Points Earned')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='buildings.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
