# Generated by Django 6.0.6 on 2026-06-16 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_unit03_building_geofence_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('geofence', 'Geofence'), ('admin', 'Admin'), ('role_access', 'Role Access')], default='geofence', max_length=20)),
                ('last_validated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='building',
            new_name='buildings_b_slug_36fc27_idx',
            old_name='buildings_b_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='building',
            new_name='buildings_b_is_acti_3c43aa_idx',
            old_name='buildings_b_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='geofence',
            new_name='buildings_g_buildin_2a4ea1_idx',
            old_name='buildings_g_buildin_idx',
        ),
        migrations.AddField(
            model_name='buildingunlock',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unlocks', to='buildings.building'),
        ),
        migrations.AddField(
            model_name='buildingunlock',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_unlocks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='buildingunlock',
            index=models.Index(fields=['user', 'building'], name='buildings_b_user_id_02212d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='buildingunlock',
            unique_together={('user', 'building')},
        ),
    ]
