# Generated by Django 6.0.6 on 2026-06-30 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='target_role',
            field=models.CharField(choices=[('all', 'All Users'), ('student', 'Students Only'), ('visitor', 'Guests/Visitors Only'), ('professional', 'Professionals Only')], default='all', max_length=20),
        ),
    ]
