# Generated by Django 6.0.6 on 2026-06-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_buildingunlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='model_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
        migrations.AddField(
            model_name='building',
            name='model_file_size',
            field=models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='model_version',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
