# Generated by Django 6.0.6 on 2026-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_quest_target_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, the quest will expire at this time (used for Timed Challenges)', null=True),
        ),
    ]
