# Generated by Django 6.0.6 on 2026-06-17 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_building_model_active_building_model_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('model', '3D Model'), ('panorama', 'Panorama Image'), ('image', 'Building Image')], max_length=20)),
                ('file', models.FileField(upload_to='assets/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('checksum', models.CharField(blank=True, default='', help_text='SHA256 hash for cache invalidation', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='buildings.building')),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['building', 'asset_type', 'is_active'], name='buildings_b_buildin_8b3dc8_idx')],
            },
        ),
    ]
