# Generated by Django 6.0.6 on 2026-06-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_quest_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='image',
            field=models.ImageField(blank=True, help_text='Auto-generated 2D thumbnail of the 3D model', null=True, upload_to='building_images/'),
        ),
    ]
