# Generated by Django 6.0.6 on 2026-06-18 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_quest_userquestprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriviaFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivia_facts', to='buildings.building')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
