# Generated by Django 6.0.6 on 2026-06-18 15:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_triviafact'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='qr_code_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='buildingunlock',
            name='source',
            field=models.CharField(choices=[('geofence', 'Geofence'), ('admin', 'Admin'), ('role_access', 'Role Access'), ('qr', 'QR Scan')], default='geofence', max_length=20),
        ),
    ]
