# Generated by Django 6.0.6 on 2026-07-07 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_userquizprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HIDDEN', 'Published (Hidden)'), ('VISIBLE', 'Published (Visible)'), ('MAINTENANCE', 'Under Construction / Maintenance')], default='DRAFT', help_text='Drafts can be saved without coordinates/slugs.', max_length=20),
        ),
    ]
