# Generated by Django 6.0.6 on 2026-06-18 15:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_building_qr_code_secret_alter_buildingunlock_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='qr_code_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
