# Generated by Django 6.0.6 on 2026-07-07 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_alter_building_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='target_role',
        ),
    ]
