# Generated by Django 6.0.6 on 2026-06-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_alter_building_qr_code_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='If false, completely hides building from app'),
        ),
        migrations.AlterField(
            model_name='building',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If false, shows building as closed/inactive'),
        ),
    ]
