# Generated by Django 6.0.6 on 2026-07-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_remove_quest_target_role'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbadge',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='userquestprogress',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='userquizprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='target_building',
        ),
        migrations.RemoveField(
            model_name='userquestprogress',
            name='quest',
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='building',
        ),
        migrations.RemoveField(
            model_name='userquizprogress',
            name='question',
        ),
        migrations.RemoveField(
            model_name='triviafact',
            name='building',
        ),
        migrations.RemoveField(
            model_name='userbadge',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userquestprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userquizprogress',
            name='user',
        ),
        migrations.DeleteModel(
            name='Badge',
        ),
        migrations.DeleteModel(
            name='Quest',
        ),
        migrations.DeleteModel(
            name='QuizQuestion',
        ),
        migrations.DeleteModel(
            name='TriviaFact',
        ),
        migrations.DeleteModel(
            name='UserBadge',
        ),
        migrations.DeleteModel(
            name='UserQuestProgress',
        ),
        migrations.DeleteModel(
            name='UserQuizProgress',
        ),
    ]
