# Generated by Django 6.0.6 on 2026-06-19 12:01

from django.db import migrations, models


def migrate_status(apps, schema_editor):
    Building = apps.get_model('buildings', 'Building')
    for building in Building.objects.all():
        if building.is_visible:
            building.status = 'VISIBLE'
        else:
            building.status = 'HIDDEN'
        building.save()

def reverse_migrate_status(apps, schema_editor):
    Building = apps.get_model('buildings', 'Building')
    for building in Building.objects.all():
        if building.status == 'VISIBLE':
            building.is_visible = True
        else:
            building.is_visible = False
        building.save()

class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_building_is_visible_alter_building_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('HIDDEN', 'Published (Hidden)'), ('VISIBLE', 'Published (Visible)')], default='DRAFT', help_text='Drafts can be saved without coordinates/slugs.', max_length=10),
        ),
        migrations.RunPython(migrate_status, reverse_migrate_status),
        migrations.RemoveField(
            model_name='building',
            name='is_visible',
        ),
        migrations.AlterField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='building',
            index=models.Index(fields=['status'], name='buildings_b_status_93224f_idx'),
        ),
    ]
