# Generated by Django 6.0.6 on 2026-06-20 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_department_building_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='department',
        ),
        migrations.AddField(
            model_name='building',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='buildings', to='buildings.department'),
        ),
        migrations.AddField(
            model_name='building',
            name='primary_department',
            field=models.ForeignKey(blank=True, help_text='Determines the map pin color', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_buildings', to='buildings.department'),
        ),
    ]
