# Generated by Django 6.0.6 on 2026-06-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_remove_building_department_building_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quest',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triviafact',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
