# Generated by Django 6.0.6 on 2026-06-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_building_deleted_at_quest_deleted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='hotspots',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
