# Generated by Django 6.0.6 on 2026-08-14 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLocationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('last_timestamp', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_tracker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
