# Generated by Django 6.0.6 on 2026-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
