# Generated by Django 6.0.6 on 2026-06-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateField(blank=True, help_text="Date of the user's last recorded login for streak tracking", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='streak_count',
            field=models.IntegerField(default=0, help_text='Consecutive daily login streak'),
        ),
    ]
