# Generated by Django 6.0.6 on 2026-06-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_emailotp_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='exploration_points',
            field=models.IntegerField(default=0, help_text='Points earned from discovering AR targets and completing quests'),
        ),
    ]
