# Generated by Django 6.0.6 on 2026-08-14 11:42

import apps.authentication.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userdevice'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.authentication.models.CustomUserManager()),
            ],
        ),
    ]
