# Generated by Django 6.0.6 on 2026-10-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Custom uploaded profile photo or avatar', null=True, upload_to='profile_images/'),
        ),
    ]
