# Generated by Django 6.0.6 on 2026-06-21 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanoramaScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='panoramas/')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_start_scene', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panorama_scenes', to='buildings.building')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PanoramaHotspot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('yaw', models.FloatField(help_text='Horizontal rotation in degrees')),
                ('pitch', models.FloatField(help_text='Vertical rotation in degrees')),
                ('is_active', models.BooleanField(default=True)),
                ('source_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='panorama.panoramascene')),
                ('target_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_hotspots', to='panorama.panoramascene')),
            ],
        ),
        migrations.AddIndex(
            model_name='panoramascene',
            index=models.Index(fields=['building', 'is_active'], name='panorama_pa_buildin_904d06_idx'),
        ),
        migrations.AddIndex(
            model_name='panoramascene',
            index=models.Index(fields=['is_start_scene'], name='panorama_pa_is_star_e18174_idx'),
        ),
        migrations.AddIndex(
            model_name='panoramahotspot',
            index=models.Index(fields=['source_scene', 'is_active'], name='panorama_pa_source__43cbe0_idx'),
        ),
    ]
