# Generated by Django 5.2.1 on 2026-09-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panorama', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panoramascene',
            name='anchor_radius',
            field=models.FloatField(default=5.0, help_text='Proximity catchment radius in meters'),
        ),
        migrations.AddField(
            model_name='panoramascene',
            name='anchor_x',
            field=models.FloatField(blank=True, help_text='3D Model local X coordinate', null=True),
        ),
        migrations.AddField(
            model_name='panoramascene',
            name='anchor_y',
            field=models.FloatField(blank=True, default=1.6, help_text='3D Model eye-level Y coordinate', null=True),
        ),
        migrations.AddField(
            model_name='panoramascene',
            name='anchor_z',
            field=models.FloatField(blank=True, help_text='3D Model local Z coordinate', null=True),
        ),
    ]
