# Generated by Django 6.0.6 on 2026-07-21 11:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0010_remove_userbadge_badge_remove_quest_target_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji icon e.g. 🏅', max_length=10)),
                ('color_hex', models.CharField(default='#FFD700', max_length=7)),
                ('trigger', models.CharField(choices=[('first_unlock', 'First Building Unlocked'), ('unlocks_5', '5 Buildings Unlocked'), ('unlocks_10', '10 Buildings Unlocked'), ('unlocks_all', 'All Buildings Unlocked'), ('first_quest', 'First Quest Completed'), ('quests_5', '5 Quests Completed'), ('quests_10', '10 Quests Completed'), ('points_100', '100 Points Earned'), ('points_500', '500 Points Earned'), ('points_1000', '1000 Points Earned')], max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'buildings_badge',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('hint', models.TextField()),
                ('reward_points', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='If set, the quest will expire at this time (used for Timed Challenges)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('target_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quests', to='buildings.building')),
            ],
            options={
                'db_table': 'buildings_quest',
            },
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buildings_userbadge',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='UserQuestProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='gamification.quest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'buildings_userquestprogress',
                'unique_together': {('user', 'quest')},
            },
        ),
    ]
