# Generated by Django 6.0.6 on 2026-06-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='ARQuest', max_length=100)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('contact_email', models.EmailField(default='support@arquest.edu', max_length=254)),
                ('enable_gps', models.BooleanField(default=True)),
                ('enable_qr', models.BooleanField(default=True)),
                ('enable_ar_selfie', models.BooleanField(default=True)),
                ('enable_trivia', models.BooleanField(default=True)),
                ('enable_accreditation', models.BooleanField(default=False)),
                ('enable_leaderboard', models.BooleanField(default=True)),
                ('default_quest_reward', models.IntegerField(default=50)),
            ],
        ),
    ]
