# Generated by Django 6.0.6 on 2026-07-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('SYSTEM', 'System Alert'), ('PROFESSIONAL', 'Professional Management'), ('BUILDING', 'Building Management'), ('FEEDBACK', 'User Feedback')], default='SYSTEM', max_length=50),
        ),
    ]
